version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://root:admin123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  myapp:
    build: .
    expose:
      - 80
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/